language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
sudo: false

script:
  - yarn lint-shim
  - yarn build-shim
  - yarn test-shim

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: "6"